##
# Basic inherited variables for terraformscaffold modules
##

variable "project" {
  type        = string
  description = "The name of the terraformscaffold project calling the module"
}

variable "environment" {
  type        = string
  description = "The name of the terraformscaffold environment the module is called for"
}

variable "component" {
  type        = string
  description = "The name of the terraformscaffold component calling this module"
}

variable "aws_account_id" {
  type        = string
  description = "The AWS Account ID (numeric)"
}

variable "group" {
  type        = string
  description = "The name of the tfscaffold group"
  default     = null
}

##
# Variable specific to the module
##

# We presume this will always be specified. The default of {} will cause an error if a valid map is not specified.
# If we ever want to define this but allow it to not be specified, then we must provide a default tag keypair will be applied
# as the true default. In any other case default_tags should be removed from the module.
variable "default_tags" {
  type        = map(string)
  description = "Default tag map for application to all taggable resources in the module"
  default     = {}
}

variable "region" {
  type        = string
  description = "The AWS Region"
}

variable "name" {
  type        = string
  description = "A unique name to distinguish this module invocation from others within the same CSI scope"
}

variable "kms_key_arn" {
  type        = string
  description = "KMS key arn to use for this function"
}

variable "log_retention_in_days" {
  type        = number
  description = "The retention period in days for the Cloudwatch Logs events generated by the lambda function"
}

variable "event_cache_buffer_interval" {
  type        = number
  description = "The buffer interval for data firehose"
  default     = 500
}

variable "enable_sns_delivery_logging" {
  type        = bool
  description = "Enable SNS Delivery Failure Notifications"
  default     = false
}

variable "sns_success_logging_sample_percent" {
  type        = number
  description = "Enable SNS Delivery Successful Sample Percentage"
  default     = 0
}

variable "log_level" {
  type        = string
  description = "The log level to be used in lambda functions within the component. Any log with a lower severity than the configured value will not be logged: https://docs.python.org/3/library/logging.html#levels"
  default     = "WARN"
}

variable "event_cache_expiry_days" {
  type        = number
  description = "s3 archiving expiry in days"
  default     = 30
}

variable "enable_event_cache" {
  type        = bool
  description = "Enable caching of events to an S3 bucket"
  default     = false
}

variable "enable_firehose_raw_message_delivery" {
  type        = bool
  description = "Enables raw message delivery on firehose subscription"
  default     = false
}

variable "force_destroy" {
  type        = bool
  description = "When enabled will force destroy event-cache S3 bucket"
  default     = false
}

variable "shared_infra_account_id" {
  type        = string
  description = "The AWS Account ID of the shared infrastructure account"
  default     = "000000000000"
}
