name: "2. CD - Deploy"

on:
  workflow_dispatch:
    inputs:
      source_type:
        description: "Deployment source type"
        type: choice
        required: true
        default: release
        options:
          - release
          - branch
      source_value:
        description: "Release tag or branch name"
        type: string
        required: true
      deploy_backend:
        description: "Deploy backend infrastructure"
        type: boolean
        required: false
        default: true
      backend_account_group:
        description: "Target backend account group"
        type: choice
        required: true
        default: dev
        options:
          - dev
          - nonprod
          - prod
      deploy_proxy:
        description: "Deploy APIM proxy"
        type: boolean
        required: false
        default: true
      apim_environment:
        description: "Target APIM environment"
        type: choice
        required: true
        default: internal-dev
        options:
          - internal-dev
          - int
          - prod
      build_sandbox:
        description: "Build sandbox container"
        type: boolean
        required: false
        default: false

run-name: >-
  Deploy ${{ inputs.deploy_backend && format('backend={0}',
  inputs.backend_account_group) || '' }} ${{ inputs.deploy_proxy &&
  format('apim={0}', inputs.apim_environment) || '' }} source=${{
  inputs.source_type }}:${{ inputs.source_value }} by @${{ github.actor }}

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-supplier-api.yaml
    secrets: inherit
    with:
      backend_account_group: ${{ inputs.backend_account_group }}
      apim_environment: ${{ inputs.apim_environment }}
      source_type: ${{ inputs.source_type }}
      source_value: ${{ inputs.source_value }}
      deploy_backend: ${{ inputs.deploy_backend }}
      deploy_proxy: ${{ inputs.deploy_proxy }}
      build_sandbox: ${{ inputs.build_sandbox }}
