name: Deploy backend only

on:
  workflow_dispatch:
    inputs:
      backend_account_group:
        description: "Target backend account group"
        type: choice
        required: true
        default: dev
        options:
          - dev
          - nonprod
          - prod
      source_type:
        description: "Deployment source type"
        type: choice
        required: true
        default: release
        options:
          - release
          - branch
      source_value:
        description: "Release tag or branch name"
        type: string
        required: true

run-name: >-
  Deploy backend=${{ inputs.backend_account_group }} source=${{
  inputs.source_type }}:${{ inputs.source_value }} by @${{ github.actor }}

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-supplier-api.yaml
    secrets: inherit
    with:
      backend_account_group: ${{ inputs.backend_account_group }}
      source_type: ${{ inputs.source_type }}
      source_value: ${{ inputs.source_value }}
      deploy_backend: true
      deploy_proxy: false
