name: Github Release Created

on:
  release:
    types: [ "released" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-supplier-api.yaml
    secrets: inherit
    with:
      source_type: release
      source_value: ${{ github.event.release.tag_name }}
      deploy_backend: true
      backend_account_group: nonprod
      deploy_proxy: true
      apim_environment: int
